Module3 task1
htmlacademy-javascript/1435443-keksobooking-21 pull request #2
Opened 2020-09-26 17:09 UTC by Misha-13

2020-09-27 15:42 UTC, tanya-chuk requested changes

2020-09-27 15:42 UTC, tanya-chuk commented on js/main.js
> +pinsList.appendChild(fragment);
Общее замечание по работе с let и const: с помощью let объявляем лишь те переменные, значения которых перезаписываются далее в коде после объявления и первичного присваивания значения, т.е. происходит что-то вроде:
```
let a = 5;
// some script
a = 10;
```

Если же перезаписи значения не происходит, значит, можно объявлять переменную с помощью const.

2020-09-27 17:27 UTC, tanya-chuk requested changes

2020-09-27 17:27 UTC, tanya-chuk commented on js/main.js
> +let fragment = document.createDocumentFragment();
переменные pinsList и fragment - тоже константы, смотри как это работает на примере pinsList:

- создаем переменную с идентификатором (именем) pinsList
- присваиваем ей значение - объект, найденный по селектору
- присваивание объектов происходит по ссылке на область памяти, содержащей этот объект. значит, значение переменной становится именно _ссылка_, ведущая к объекту с его содержимым 
- при изменении объекта (что и происходит дальше в коде, когда объекту, к которому мы обращаемся с помощью ссылки pinsList, добавляются атрибуты, новые свойства) сама ссылка на него остается неизменной, поэтому данная переменная может быть объявлена с помощью const

надеюсь, смогла понятно объяснить! пиши в телегу, если остались сомнения :)

2020-09-27 17:27 UTC, tanya-chuk commented on js/main.js
> +    let y = createValueInRange(MIN_Y, MAX_Y);
x и y - const

2020-09-27 17:27 UTC, tanya-chuk commented on js/main.js
> +  let pinElement = pinTemplate.cloneNode(true);
pinElement - const, поскольку работаем с ссылкой на объект dom-узла

2020-09-27 17:27 UTC, tanya-chuk commented on js/main.js
> +        'y': y,
Смещение, связанное с размерами тела метки, стоит учесть уже здесь, иначе некоторые метки подвисают в воздухе:
![Uploading Снимок экрана 2020-09-27 в 20.26.04.png…]()

2020-09-27 18:43 UTC, Misha-13 commented on js/main.js
> +    let y = createValueInRange(MIN_Y, MAX_Y);
Это из-за того, что внутри цикла не происходит переопределения переменной?

2020-09-27 18:50 UTC, Misha-13 commented on js/main.js
> +        'y': y,
Поднял границу в генерации координат. Мне кажется, что на 130px по Y нельзя наводиться, если использовать смещение на размер пина, так как можно на надпись попасть и перекрыть ее.

2020-09-28 08:43 UTC, tanya-chuk commented on js/main.js
> +    let y = createValueInRange(MIN_Y, MAX_Y);
да, по сути они заново создаются для каждой итерации

2020-09-28 08:44 UTC, tanya-chuk approved these changes

2020-09-28 08:44 UTC, merged