Module4 task1
htmlacademy-javascript/1435443-keksobooking-21 pull request #4
Opened 2020-10-17 20:04 UTC by Misha-13

2020-10-18 11:14 UTC, tanya-chuk requested changes

2020-10-18 11:14 UTC, tanya-chuk commented on js/main.js
> +    checkNotEqualsSelectorsValue();
По идее проверка этих селекторов должна осуществляться не при активации страницы, а лишь на каждый submit. Сейчас эта функция срабатывает преждевременно, как бы наперед

2020-10-18 11:14 UTC, tanya-chuk commented on js/main.js
> +  mainPin.addEventListener(`keydown`, activateElements);
Именование функции обработчика нарушает критерий Д4

2020-10-18 11:14 UTC, tanya-chuk commented on js/main.js
> +  checkNotEqualsSelectorsValue();
эти обработчики не обязательно заворачивать в анонимную функцию, их логика уже вынесена в функцию-обработчик. Только обрати внимание на нейминг - нарушает критерий Д4

2020-10-18 11:14 UTC, tanya-chuk commented on js/main.js
> +    removeActivateEvents();
здесь можно не заворачивать функцию-обработчик в анонимную функцию (+нейминг по Д4!)

2020-10-18 11:14 UTC, tanya-chuk commented on js/main.js
> +      removeActivateEvents();
Здесь тоже предлагаю вынести логику для нажатия на Enter в отдельную функцию-обработчик, которая будет запускать removeActivateEvents при нажатии на нужную клавишу, и вызывать ее здесь. Так код лучше читается - мол, вот тебе триггер события, а что произойдет, можно посмотреть вот в этой функции

2020-10-18 16:18 UTC, tanya-chuk requested changes

2020-10-18 16:18 UTC, tanya-chuk commented on js/main.js
> +  if (isMainMouseButton(evt)) {
проверка на isMainMouseButton избыточна, тк обработчик уже установлен на кнопку

2020-10-18 16:18 UTC, tanya-chuk commented on js/main.js
> +blockPage();
Сейчас поведение валидатора не соответсвует пункту 2.4 ТЗ: при попытке некорректного ввода данных по количеству комнат/гостей валидатор отрабатывает сразу же. Согласно ТЗ валидатор начинает ругаться при попытке отправить форму

2020-10-18 16:18 UTC, tanya-chuk commented on js/main.js
> +blockPage();
обрати еще раз внимание на ТЗ 3.4 :)

2020-10-18 16:18 UTC, tanya-chuk commented on js/main.js
> +  } else if (capacitySelector.value === `0` && roomsSelector.value === `100`) {
Критерий Д15: можно воспользоваться конструкцией if/return:
```

if (conditon1) {
  return result1;
}
if (condition2) {
  return result2;
}

```

2020-10-18 16:18 UTC, tanya-chuk commented on js/main.js
> +  if (capacitySelector.value <= roomsSelector.value && !(capacitySelector.value === `0` || roomsSelector.value === `100`)) {
`capacitySelector.value === 0 && roomsSelector.value === 100`
Этот кусок кода повторяется, его можно вынести в переменную для краткого обращения и для оптимизации расчетов (посчитается один раз во время присваивания переменной значения)

2020-10-18 16:18 UTC, tanya-chuk commented on js/main.js
> +const X_SHIFT_MOVEABLE_PIN = HALF_DISABLED_PIN_SIZE;
можно сразу воспользоваться значением HALF_DISABLED_PIN_SIZE

2020-10-18 16:18 UTC, tanya-chuk commented on js/main.js
> +  if (isMainMouseButton(evt)) {
здесь тоже можно не проверять isMainMouseButton

2020-10-18 17:33 UTC, Misha-13 commented on js/main.js
> +  if (isMainMouseButton(evt)) {
У меня без этого условия не выполнится вот эта часть из задания
 "Обратите внимание, что событие mousedown срабатывает при нажатии любой кнопки мыши, а нас интересует только основная кнопка (обычно — левая). Поэтому необходимо добавить дополнительную проверку свойства button объекта события mousedown. Подробнее о свойстве на MDN."

Либо я проверяю как-то криво =))

2020-10-18 17:35 UTC, Misha-13 commented on js/main.js
> +  } else if (capacitySelector.value === `0` && roomsSelector.value === `100`) {
Имеется ввиду, что будет передаваться строка в параметр метода setCustomValidity, а данная функция будет просто определять вид сообщения?

2020-10-19 07:45 UTC, tanya-chuk commented on js/main.js
> +  } else if (capacitySelector.value === `0` && roomsSelector.value === `100`) {
Смотри, логика тут особо не меняется, рассмотри пример из критерия - это способ минимизировать скрипт с сохранением читаемости. Логика реализуется не через if/else, а через if/return - то есть ты даешь понять, что если случился сценарий, описанный в условии, то можно выполнить соответсвующий блок кода и затем сразу совершить выход из функции. То есть по факту да, как и сейчас, условие определяет вид сообщения, а теле в setCustomValidity передается строка)

2020-10-19 08:08 UTC, tanya-chuk requested changes

2020-10-19 08:08 UTC, tanya-chuk commented on js/main.js
> +  if (isMainMouseButton(evt)) {
По условию ок, принято :) но в проверке isMainMouseButton есть избыточность, связанная с явным описанием поведения по умолчанию (возвращение true/false). Достаточно будет проверить тут evt.button === 0 (+ значение 0 можно положить в константу, чтобы избежать появления "магических значений" - критерий Д19

2020-10-20 17:56 UTC, tanya-chuk requested changes
Осталось еще немного доработать валидацию соответствия количества комнат и гостей по ТЗ: сейчас на вариант "не для гостей" можно отправить любое количество комнат, а по ТЗ - только вариант "100 комнат". В остальном все хорошо!

2020-10-21 17:22 UTC, tanya-chuk approved these changes

2020-10-21 17:23 UTC, merged