Module4 task2
htmlacademy-javascript/1435443-keksobooking-21 pull request #5
Opened 2020-10-23 15:04 UTC by Misha-13

2020-10-23 15:29 UTC, Misha-13 commented
Сильно не ругай =))

2020-10-25 10:55 UTC, tanya-chuk requested changes

2020-10-25 10:55 UTC, tanya-chuk commented on js/main.js
> +const TypeMinCostMatch = {
Нужно поправить именование по критерию Б8 (значения перечислений должны быть объявлены как константы)

2020-10-25 10:55 UTC, tanya-chuk commented on js/main.js
> +  if (evt.key === `Escape`) {
Предлагаю на этом этапе положить значения клавиш в перечисление: уже есть escape и enter

2020-10-25 10:55 UTC, tanya-chuk commented on js/main.js
> +let selectingPin = [];
Переменную selectingPin лучше объявить внутри функции, которая ее использует

2020-10-25 10:55 UTC, tanya-chuk commented on js/main.js
> +  setPinEvent(selectingPin, `map__pin--main`);
значения selectingPin и `map__pin--main` больше никуда не передаются, поэтому лучше их определить непосредственно внутри функции setPinEvent - это будут ее локальные переменные

2020-10-25 10:55 UTC, tanya-chuk commented on js/main.js
> +      currentArr[i].addEventListener(`click`, function () {
здесь много логики, для улучшения читаемости лучше вынести ее в функцию-обработчик

2020-10-25 10:55 UTC, tanya-chuk commented on js/main.js
>  const onFormElementsActivate = function () {
внутри этой функции уже много всего происходит, предлагаю выделить в ней логические блоки (например, рендер пинов, назначение валидаторов...), вынести их в функции и в onFormElementsActivate лишь собрать их вызовы.
И еще один момент с неймингом - onFormElementsActivate уже не используется в коде как функция-обработчик, обработкой событий занимаются onPinKeydown/Mousedown. Поэтому будет правильнее переименовать ее в соответствии с критерием Б6

2020-10-25 10:55 UTC, tanya-chuk commented on js/main.js
> +    document.mapAreaElement.remove();
здесь можно воспользоваться готовой функцией removeExistPin

2020-10-25 10:55 UTC, tanya-chuk commented on js/main.js
> +  document.mapAreaElement = mapArea.querySelector(`.map__card`);
Думаю, будет правильнее сохранять mapAreaElement не через присваивание в свойство document, а через создание переменной

2020-10-25 10:55 UTC, tanya-chuk commented on js/main.js
> +  document.mapAreaElement = mapArea.querySelector(`.map__card`);
Здесь как и в removeExistPin, лучше воспользоваться переменной вместо работы с document

2020-10-25 10:55 UTC, tanya-chuk commented on js/main.js
> +const onExitButtonClick = function () {
Именование должно быть по Б6

2020-10-25 13:00 UTC, tanya-chuk requested changes

2020-10-25 13:00 UTC, tanya-chuk commented on js/main.js
> +  if (KeysList[evt.key.toUpperCase()]) {
здесь как и в onInfoPinKeydown, лучше через сравнение

2020-10-26 16:14 UTC, tanya-chuk requested changes

2020-10-26 16:14 UTC, tanya-chuk commented on js/main.js
> +        onInfoPinClick(i, exceptionCounter);
Здесь предлагаю тебе передавать в onInfoPinClick текущий пин, с которым эта функция будет работать. После проверки if нужно будет получить текущий пин, например, в переменной currentPin, а затем передать его в onInfoPinClick.

Так ты изолируешь логику этой функции, у нее будет одна простая задача - взять данные и с ними отрисовать карточку. А то, каким образом эти данные были вытащены (с помощью i и exceptionCounter) - это более высокий уровень абстракции, который ее не интересует; этим уровнем занимается renderPinCard со всеми ее циклами и счетчиками.

(кстати, нейминг onInfoPinClick нужно поправить в соответствии с Б6, тк это уже не обработчик: обработчиком стала анонимная функция
`function () { onInfoPinClick((i, exceptionCounter);}`, а сама onInfoPinClick - обычная функция, которая вызывается изнутри обработчика)

2020-10-26 16:14 UTC, tanya-chuk commented on js/main.js
> +  cardFragment.appendChild(fillCards(document.mapPins[counter - exceptionCounter]));
Получается, на этом этапе две цели:

- избавиться от обращения к document.mapPins
- вынести логику получения данных по нужному пину на уровень выше

В итоге сюда будет просто прилетать объект, который прокидывается в fillCards.

2020-10-27 15:18 UTC, tanya-chuk approved these changes
По красоте!

2020-10-27 15:19 UTC, merged