Добавляет загрузку данных на сервер
htmlacademy-javascript/1435443-keksobooking-21 pull request #9
Opened 2020-11-03 14:27 UTC by Misha-13

2020-11-04 11:06 UTC, tanya-chuk requested changes

2020-11-04 11:06 UTC, tanya-chuk commented on js/upload.js
> +})();
Заметила несоответствие объявления функций критерию Д28: поскольку используем const/let вместо var, нужно соблюдать также стрелочный синтаксис функций, для функций, где не используется контекст. Нужно поправить: 
```
function () {}
function (a, b) {}
```
становится
```
() => {}
(a, b) => {}
```

2020-11-04 17:12 UTC, Misha-13 commented on index.html
> +  <script src="js/upload.js"></script>
Это не баг, а это я дурачок =)) Удалил строку с проверкой полей при отправке формы. Сейчас все ок должно быть.

2020-11-05 13:48 UTC, tanya-chuk requested changes

2020-11-05 13:48 UTC, tanya-chuk commented on js/load.js
> +        case window.utility.StatusCode.OK:
Здесь можно выполнить деструктуризацию, чтобы вытащить значения перечисления StatusCode:
`
const {  OK, BAD_REQUEST, NOT_FOUND } = window.utility.StatusCode;
`
А затем кратко обращаться к этим значениям:
`case BAD_REQUEST:`

Это не замечание, скорее улучшение и демонстрация возможностей es6 - можешь использовать этот прием, мне лично очень нравится - код становится лаконичнее

2020-11-05 13:48 UTC, tanya-chuk commented on js/load.js
> +    xhr.open(window.utility.SERVER_REQUEST.get.method, window.utility.SERVER_REQUEST.get.url);
а здесь прямо просится деструктуризация! вытащи как в примере выше url и method и оцени, насколько сократится запись :)

2020-11-05 13:48 UTC, tanya-chuk commented on js/utility.js
> +  const SERVER_REQUEST = {
эта структура по природе скорее перечисление - набор именованных значений. поэтому нужно немного поправить нейминг (нотации) в соответсвии с критериями

2020-11-05 13:48 UTC, tanya-chuk commented on js/upload.js
> +    xhr.open(window.utility.SERVER_REQUEST.post.method, window.utility.SERVER_REQUEST.post.url);
как и в load.js - здесь будет классно использовать деструктуризацию

2020-11-05 16:00 UTC, tanya-chuk approved these changes

2020-11-05 16:00 UTC, tanya-chuk commented on js/upload.js
> +      const isSuccess = (xhr.status === window.utility.StatusCode.OK);
тут можно опустить скобки, в следующем коммите)

2020-11-05 16:00 UTC, merged